# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
name: raimund
email: raimund@rittnauer.at
description: >
  Blog mostly about tech related stuff

url: "https://raaaimund.github.io"
baseurl: ""
last_updated: # leave blank if you don't want to display last updated

google_analytics: "UA-25417012-4"

# -----------------------------------------------------------------------------
# jekyll-seo-tag
# -----------------------------------------------------------------------------
defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/favicons/android-chrome-256x256.png
logo: /assets/img/favicons/android-chrome-192x192.png
social:
  name: Raimund Rittnauer
  links:
    - https://github.com/raaaimund

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
github_username:  raaaimund

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------
blog_name: Hi

# Pagination
paginate: 4
permalink: pretty

text:
  pagination:
    newer: 'Newer'
    older: 'Older'

disqus_shortname: raaaimund

show_social_icons:  false
enable_anchorjs:    true
enable_katex:       true

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    permalink: /:collection/:title/

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

markdown: kramdown
highlighter: rouge

include: ['_pages']
include: ['assets']
exclude: [vendor]

plugins:
    - jekyll-email-protect
    - jekyll-paginate
    - jekyll/scholar
    - jekyll-seo-tag
    - jekyll-sitemap
    - jemoji

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
katex_version: "0.15.3"
anchorjs_version: "3.2.2"
