# Site settings
title: "R"
email: raimund@rittnauer.at
description: "R's Blog."
baseurl: ""
url: "http://raaaimund.github.io"
title_description: "A blog about everything that comes in my mind."
title_image: "https://raw.githubusercontent.com/raaaimund/raaaimund.github.io/master/img/me.jpg"
google_analytics: "UA-25417012-4"
disqus_account: raaaimund
github_repository: https://github.com/raaaimund/raaaimund.github.io
addthis_id: ra-5751945adf840e71
post_limit: 5

# Social usernames/URLs
twitter_username: raaaimund
github_username:  raaaimund
google_plus_link: https://plus.google.com/u/0/+RaimundRittnauer

# Footer
footer_left: "With <i class=\"fa fa-heart\"></i> by <a href=\"https://github.com/raaaimund\">Raimund</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/raaaimund/raaaimund.github.io\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]

gems:
  - jekyll-sitemap
  - jekyll-seo-tag