# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
name: raimund
email: raimund@rittnauer.at
description: >
  My Github Page

url: "https://raaaimund.github.io"
baseurl: ""
last_updated: # leave blank if you don't want to display last updated

google_analytics: "UA-25417012-4"

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
github_username:  raaaimund

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------
blog_name: Hi
blog_description:

# Pagination
paginate: 4
permalink: pretty

text:
  pagination:
    newer: 'Newer'
    older: 'Older'

disqus_shortname: raaaimund

show_social_icons:  false
enable_anchorjs:    true
enable_katex:       true

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  pages:
    output: true
    permalink: /:path/

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

markdown: kramdown
highlighter: pygments

include: ['_pages']
include: ['assets']
exclude: [vendor]

plugins:
    - jekyll-email-protect
    - jekyll-paginate
    - jekyll/scholar
    - jemoji

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
katex_version: "0.9.0"
anchorjs_version: "3.2.2"
