version: '3.3'
services:
   blog:
    build:
      context: .
    volumes:
      - './:/srv/jekyll'
    ports:
      - '4000:4000'
      - '35729:35729'
    command: jekyll serve --livereload --force_polling